- name: Deploy Docker Container
  hosts: all
  become: true
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: myapp:latest
        source: pull

    - name: Run Docker Container
      docker_container:
        name: myapp
        image: myapp:latest
        state: started
        ports:
          - "8080:80"
